[package]
name = "users_canister"
version = "0.1.0"
edition = "2021"


[dependencies]
candid = { workspace = true }
ic-cdk = { workspace = true }
ic-cdk-macros = { workspace = true }
serde = { workspace = true }
types = { path = "../../../libraries/types" }
